bracketSpacing: true
jsxBracketSameLine: true
printWidth: 120
semi: true
singleQuote: false
tabWidth: 2
trailingComma: all
useTabs: false
overrides:
  - files: "*.ts"
    options:
      parser: typescript
